# Generated by Django 3.2.7 on 2021-10-29 20:09

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cat', '0004_alter_cat_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Extra',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='User_Extra_FK', serialize=False, to='auth.user')),
                ('about', models.CharField(max_length=200)),
                ('birthdate', models.DateField(blank=True)),
                ('header', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
            ],
        ),
    ]
