# Generated by Django 3.2.7 on 2021-11-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_auto_20211103_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_location',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ip_location',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
