# Generated by Django 3.2.7 on 2021-11-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0008_auto_20211103_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extra',
            name='header',
            field=models.FileField(upload_to='media/'),
        ),
    ]
