# Generated by Django 3.2.7 on 2021-11-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0009_alter_user_extra_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extra',
            name='header',
            field=models.FileField(upload_to='cat/headers/'),
        ),
    ]
