# Generated by Django 3.2.7 on 2021-11-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0010_alter_user_extra_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='bodyBLRadius',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='bodyBRRadius',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='bodyColor',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='bodyHeight',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='bodyTLRadius',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='bodyTRRadius',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='bodyTatoo',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='bodyWidth',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='faceColor',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='headAlign',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='headGlowColor',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='headSize',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='neckLength',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='neckWidth',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='tailColor',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='tailLength',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='tatooColor',
        ),
    ]
