# Generated by Django 3.2.7 on 2021-11-10 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0011_auto_20211110_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adoptDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='body_arc',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='body_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='body_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='body_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='ear_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='ear_direction',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='ear_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='ear_offset',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='ear_width',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='eye_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='eye_distance',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='eye_height',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='eye_margin_top',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='eye_width',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='head_arc',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='head_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='head_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='head_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='neck_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='neck_length',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='neck_width',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='retina_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='retina_height',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='retina_width',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='cat',
            name='tail_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='tail_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='tail_stroke',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='tail_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='catAge',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='catDesc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='catHappiness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='catHealth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='catName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='catWeight',
            field=models.IntegerField(null=True),
        ),
    ]
