# Generated by Django 3.2.7 on 2021-11-16 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat', '0013_auto_20211110_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('followed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_FK', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('message', models.TextField(default='Hi, I want to borrow your cat:)')),
                ('status', models.IntegerField(default=0)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_borrower_FK', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_owner_FK', to=settings.AUTH_USER_MODEL)),
                ('target_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_target_cat_FK', to='cat.cat')),
            ],
        ),
    ]
