# Generated by Django 3.2.7 on 2021-11-22 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat', '0015_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Love',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loved_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('love_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.cat')),
            ],
        ),
    ]
